// mothership:dev-only
//
// Plans the board-motion figures: every pose of every character as an SVG file under
// design/board-motion/assets/figures/, and the poses the board draws as one stylesheet bundle
// (board-motion.figures.css), so that drawing a pose never fetches one. Called by
// design/tools/board-motion-assets.mjs, which writes and checks what this returns.

import { createHash } from 'node:crypto';
import { canvas } from './rig.mjs';
import { CREW } from './crew.mjs';
import { POSES } from './poses.mjs';

export const FIGURE_VERSION = 'board-motion-0.2.0';
const OUT = 'design/board-motion/assets/figures';
/** The poses the board draws, all of them for every character, loaded once whatever happens. */
export const BOARD_POSES = ['standing', 'standingFolded', 'standingBack', 'walking', 'leaning', 'inBed', 'onBench', 'out'];
const sha = content => createHash('sha256').update(content).digest('hex');
/**
 * An SVG as the body of a data URI: no header or comment, single quotes for its attributes,
 * and only the characters a URL cannot carry escaped, which keeps the bundle near the files' size.
 */
const dataUri = svg => svg.replace(/<\?xml[^>]*>\n/, '').replace(/<!--[\s\S]*?-->\n?/, '').replace(/\s*\n\s*/g, ' ').replace(/"/g, "'")
  .replace(/%/g, '%25').replace(/#/g, '%23').replace(/</g, '%3C').replace(/>/g, '%3E').trim();
const colorsOf = svg => [...new Set([...svg.matchAll(/(?:fill|stroke)="(#[0-9A-Fa-f]{6})"/g)].map(match => match[1].toUpperCase()))].sort();

export function planFigures() {
  const files = new Map();
  const entries = [];
  for (const [id, character] of Object.entries(CREW)) {
    for (const [pose, spec] of Object.entries(POSES)) {
      const cv = canvas(`${id}-${pose}`);
      spec.draw(cv, character);
      const about = `${character.sign} (${id}), ${pose}: ${spec.about}.`;
      for (const layer of cv.hasFront() ? ['body', 'front'] : ['body']) {
        const name = layer === 'front' ? `${id}-${pose}.front` : `${id}-${pose}`;
        const header = [
          `  Mothership · board-motion proposal ${FIGURE_VERSION.split('-').pop()} · figure ${name} · generated, do not edit`,
          `  ${about}${layer === 'front' ? ' The part laid over the room\'s prop.' : ''}`,
          `  Drawn from design/board-motion/figures/ (rig.mjs, crew.mjs, poses.mjs) by design/tools/board-motion-assets.mjs,`,
          `  after the approved standee design/source/crew/crew-${id.slice(1)}.svg, in its own colors (design tokens 0.4.0, color.crew.${id}).`,
          '  Not in the reviewed manifest design-0.2.0.',
        ].join('\n');
        const svg = cv.svg({ viewBox: spec.viewBox, width: spec.width, height: spec.height, header, layer });
        const file = `${OUT}/${name}.svg`;
        files.set(file, svg);
        entries.push({
          id: `figure.${name}`, file, character: id, pose, layer, bundled: BOARD_POSES.includes(pose),
          viewBox: spec.viewBox, anchor: spec.anchor, head: spec.head, colors: colorsOf(svg),
          bytes: Buffer.byteLength(svg), sha256: sha(svg), intendedBundle: 'public-board', audience: 'public',
          proposedExportVariant: `piece-crew.figure-${pose}${layer === 'front' ? '-front' : ''}-${id}`,
        });
      }
    }
  }
  // One stylesheet holds every pose the board draws, for every character, as a bundle does.
  const bundled = entries.filter(entry => entry.bundled);
  const css = `/* mothership:dev-only · board-motion proposal ${FIGURE_VERSION.split('-').pop()} · the nine figures in every pose the board draws · generated by design/tools/board-motion-assets.mjs, do not edit.
   Public art only. Loaded once, before the first match view, whatever the seat's role, state or turn; every rule that draws it waits for [data-art~="board-motion-figures"]. */
:root {
${bundled.map(entry => `  --bm-${entry.id.replace('.', '-').replace('.front', '-front')}: url("data:image/svg+xml,${dataUri(files.get(entry.file))}");`).join('\n')}
}
`;
  files.set('design/board-motion/assets/board-motion.figures.css', css);
  return { files, entries, css, sha: sha(css), bytes: Buffer.byteLength(css) };
}
