// Generates docs/balance/scenario-traceability.md from the pinned scenario matrix, the rulebook,
// the decision register and the scenario files. With --check it verifies the committed file.
// Every rule that no ready scenario exercises must carry a stated reason, or this script fails.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseDecisionRegister, parseRulebook } from '@mothership/balance';
import { loadGroup } from '../../../tests/scenarios/v1/files.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const target = join(root, 'docs/balance/scenario-traceability.md');
const text = path => readFileSync(join(root, path), 'utf8');
const MODES = [7, 8, 9];
const matrix = JSON.parse(text('docs/balance/scenario-matrix.json'));
const rules = parseRulebook(text('docs/balance/game-rules.md')).entries;
const decisions = parseDecisionRegister(text('docs/balance/rules-audit-v1.md')).entries;
const scenarios = Object.fromEntries(MODES.map(mode => [mode, loadGroup(String(mode)).scenarios]));
const unsupported = loadGroup('unsupported').scenarios;
const code = scenario => scenario.id.replace(/^V1-(M\d|UX)-/, '');

// Scenario codes with the modes they exist in, for example "SETUP-01" or "OFF-02 (9)".
function listed(filter) {
  const modesByCode = new Map();
  for (const mode of MODES) for (const scenario of scenarios[mode].filter(filter)) modesByCode.set(code(scenario), [...(modesByCode.get(code(scenario)) ?? []), mode]);
  return [...modesByCode.entries()].map(([name, modes]) => (modes.length === 3 ? name : `${name} (${modes.join(', ')})`)).join(', ');
}

const NOT_EXERCISED = {
  'R-SETUP-06': 'Physical components: seat cards and numbered tokens. Evidence comes from the table and from Designer.',
  'R-SETUP-15': 'Nothing to exercise: neither the fixtures nor the protocol contain a power pack.',
  'R-SETUP-16': 'A selection method cannot be shown by single cases. D21 asks the owner to confirm it.',
  'R-HACK-04': 'Conduct rule. Manual case HACK-07.',
  'R-HACK-05': 'Conduct rule. Manual case HACK-07.',
  'R-HACK-06': 'Nothing to exercise: the protocol has no messaging command. Checked by reading.',
  'R-WIN-08': 'Unreachable by legal play in every mode (audit, S-05). No fixture is possible without a synthetic state, which this baseline does not use.',
  'R-OPS-01': 'Service behaviour. Manual case OPS-02; Backend owns the tests.',
  'R-OPS-03': 'Service behaviour. Manual case OPS-02; Backend owns the tests.',
  'R-POW-01': 'Nothing to exercise: powers are off in every fixture.',
};
const OTHER_MODE = { 'R-SETUP-02': [7], 'R-SETUP-03': [8], 'R-SETUP-04': [9], 'R-ROLE-06': [8, 9], 'R-ROLE-11': [9], 'R-SHOW-09': [9] };

const lines = [];
const say = line => { lines.push(line); };
say('# Scenario traceability');
say('');
say('Generated by `npm run traceability --workspace @mothership/balance` from the scenario files, the rulebook, the decision register and the pinned matrix. Do not edit by hand; `npm run check` fails when it is out of date.');
say('');
say('A scenario is a fixture: recorded inputs and an expected result. Whether a fixture has been executed, and against what, is in [evidence/](evidence/). Nothing on this page is a result.');
say('');
say('## Fixtures per mode');
say('');
say('The three modes are separate files and separate evidence. They are never added together to claim coverage of "the game".');
say('');
say('| File | Mode | Ready | Blocked | Manual | Total |');
say('| --- | --- | --- | --- | --- | --- |');
const countBy = (list, status) => list.filter(scenario => scenario.status === status).length;
for (const mode of MODES) say(`| \`tests/scenarios/v1/mode-${mode}.scenarios.json\` | ${mode} players | ${countBy(scenarios[mode], 'ready')} | ${countBy(scenarios[mode], 'blocked')} | ${countBy(scenarios[mode], 'manual')} | ${scenarios[mode].length} |`);
say(`| \`tests/scenarios/v1/unsupported.scenarios.json\` | Configurations the rules do not allow | ${countBy(unsupported, 'ready')} | 0 | 0 | ${unsupported.length} |`);
say('');
say('Ready means the expected result is derived from decided rules and can be executed. Blocked means the case waits for an owner decision and asserts nothing. Manual means the evidence must come from the service, the user interface or people, not from an engine run.');
say('');
say('## From the earlier matrix to this baseline');
say('');
say('`docs/balance/scenario-matrix.json` of 26 September 2026 holds 35 specifications: 25 ready for implementation and 10 blocked. It is pinned and unchanged. Each one is carried into every mode it names. Scenario names below omit the `V1-M7-`, `V1-M8-` or `V1-M9-` prefix; a name without a mode list exists in all three.');
say('');
say('| Earlier ID | Earlier specification | Then | Now | Scenarios |');
say('| --- | --- | --- | --- | --- |');
for (const item of matrix.scenarios) {
  const carried = scenario => scenario.lineage.includes(item.id);
  const statuses = new Set(MODES.flatMap(mode => scenarios[mode].filter(carried).map(scenario => scenario.status)));
  const then = item.status === 'blocked_rule_decision' ? `Blocked on ${item.decision_ids.join(', ')}` : 'Ready';
  const now = statuses.has('blocked') && statuses.size === 1 ? `Still blocked on ${[...new Set(MODES.flatMap(mode => scenarios[mode].filter(carried).flatMap(scenario => scenario.decisionIds)))].join(', ')}`
    : item.status === 'blocked_rule_decision' ? 'Decided by the owner; ready' : statuses.has('manual') ? 'Ready, part manual' : 'Ready';
  const ux = unsupported.filter(carried).map(code);
  say(`| ${item.id} | ${item.title} | ${then} | ${now} | ${listed(carried)}${ux.length > 0 ? `; unsupported configurations ${ux.join(', ')}` : ''} |`);
}
say('');
say('## Open decisions and the cases that wait for them');
say('');
say('A blocked case has no expected result. Where a probe is listed, a run records what an engine does today; that is an observation, never a pass.');
say('');
say('| Decision | Question | Blocked scenarios | Probe |');
say('| --- | --- | --- | --- |');
for (const decision of decisions.filter(entry => entry.status === 'OPEN')) {
  const waits = scenario => scenario.status === 'blocked' && scenario.decisionIds.includes(decision.id);
  const probed = MODES.some(mode => scenarios[mode].filter(waits).some(scenario => scenario.steps.some(step => step.op === 'probe' || step.op === 'note')));
  say(`| ${decision.id} | ${decision.topic} | ${listed(waits)} | ${probed ? 'Yes' : 'None possible'} |`);
}
say('');
say('## Working readings and the scenarios that touch them');
say('');
say('A working reading is a DERIVED rule that cites a decision the owner is asked to confirm. The third column lists the ready scenarios whose expected result is about the rule. The fourth counts the further ready scenarios, for 7, 8 and 9 players, whose lead-up relies on it; each scenario names those rules in its `dependsOn` field. If the owner answers a reading differently, both groups are derived again.');
say('');
say('| Decision | Rules | Scenarios that assert the reading | Further scenarios that use it on the way |');
say('| --- | --- | --- | --- |');
for (const decision of decisions.filter(entry => entry.status === 'CONFIRM')) {
  const ids = rules.filter(rule => rule.refs.some(ref => ref.kind === 'decision' && ref.key === decision.id)).map(rule => rule.id);
  if (ids.length === 0) { console.error(`${decision.id} is a working reading that no rule cites`); process.exit(1); }
  const asserts = scenario => scenario.status === 'ready' && scenario.ruleRefs.some(id => ids.includes(id));
  const uses = scenario => scenario.status === 'ready' && !asserts(scenario) && scenario.dependsOn.some(id => ids.includes(id));
  say(`| ${decision.id} | ${ids.join(', ')} | ${listed(asserts) || 'None: see the next table'} | ${MODES.map(mode => scenarios[mode].filter(uses).length).join(', ')} |`);
}
say('');
say('## Rules that no ready scenario exercises');
say('');
say('Every other rule of the rulebook that is not OPEN is cited by at least one ready scenario in each mode it applies to.');
say('');
say('| Rule | Modes without a ready scenario | Why |');
say('| --- | --- | --- |');
const missing = [];
for (const rule of rules.filter(entry => entry.status !== 'OPEN')) {
  const applies = OTHER_MODE[rule.id] ?? MODES;
  const without = applies.filter(mode => !scenarios[mode].some(scenario => scenario.status === 'ready' && scenario.ruleRefs.includes(rule.id)));
  if (without.length === 0) continue;
  const reason = NOT_EXERCISED[rule.id];
  if (reason === undefined) { missing.push(`${rule.id} (modes ${without.join(', ')})`); continue; }
  say(`| ${rule.id} | ${without.join(', ')} | ${reason} |`);
}
if (missing.length > 0) {
  console.error(`Rules with no ready scenario and no stated reason: ${missing.join('; ')}`);
  process.exit(1);
}
say('');
say('## Cases with no counterpart in the earlier matrix');
say('');
say(`${listed(scenario => scenario.lineage.length === 0)}.`);
say('');
const output = `${lines.join('\n')}`;

if (process.argv.includes('--check')) {
  let current = null;
  try { current = readFileSync(target, 'utf8'); } catch { /* missing */ }
  if (current !== output) { console.error('docs/balance/scenario-traceability.md is out of date. Run: npm run traceability --workspace @mothership/balance'); process.exit(1); }
  console.log('Scenario traceability is current.');
} else {
  writeFileSync(target, output);
  console.log(`Wrote ${target}`);
}
