// mothership:dev-only
// Generated by design/tools/build-exports.mjs. Do not edit by hand.
// SYNTHETIC STUDIES. Only the pages that review them may import this module.
export const STUDY_MANIFEST_VERSION = "studies-0.1.0";
export const STUDY_STYLESHEET = "/studies/studies.art.59faf45929.css";
export const STUDIES = {
  "study-resolved-shot:study": "/studies/study-resolved-shot.study.1c3327a528.svg",
  "study-blocked-outcome:study": "/studies/study-blocked-outcome.study.ac0baf303a.svg"
};
