// mothership:dev-only
// Generated by design/tools/build-exports.mjs from packages/design-tokens/src/tokens-0.3.0.json. Do not edit by hand.
export const TOKEN_VERSION = "0.3.0";
export const PALETTE = {
  "canvas": "#10141C",
  "panel": "#202837",
  "paper": "#F4EBDD",
  "ink": "#151923",
  "textPrimary": "#F4EBDD",
  "textSecondary": "#B9C4D3",
  "publicToken": "#C6CDD4",
  "interactiveAccent": "#F1B84B",
  "focusRing": "#FFD36D",
  "paperShade": "#E3D6C2",
  "paperDeep": "#CBBBA2",
  "steel.deep": "#222B3A",
  "steel.shadow": "#34415A",
  "steel.mid": "#55657E",
  "steel.light": "#8696AE",
  "steel.pale": "#B9C4D3",
  "factionPrivateOrRevealed.blue": "#70AFFF",
  "factionPrivateOrRevealed.red": "#FF8C8C",
  "factionPrivateOrRevealed.alien": "#C4A4FF"
};
