// Plans the generated design documents. Pure: reads the contract files and the manifest and
// returns the Markdown that docs/design/ must contain, without writing anything.
// write-docs.mjs writes that plan; check-assets.mjs compares it with what is on disk.
//
// The contract files are the source. These pages are for reading them.

import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const cell = value => String(value ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ');
const row = cells => `| ${cells.map(cell).join(' | ')} |`;
const table = (head, rows) => [row(head), row(head.map(() => '---')), ...rows.map(row)].join('\n');
const code = value => `\`${value}\``;
const generated = sources => `<!-- Generated by design/tools/write-docs.mjs from ${sources.join(', ')}. Do not edit by hand: change the source and run \`npm run build:docs --workspace @mothership/design-tokens\`. -->`;
const SURFACE = { table: 'Table', 'phone-public': 'Phone, public layer', 'phone-private': 'Phone, private sheet' };

export async function planDocs({ repoRoot, manifest, studyManifest }) {
  const json = async path => JSON.parse(await readFile(resolve(repoRoot, path), 'utf8'));
  const states = await json('design/contract/component-states.json');
  const cues = await json('design/contract/motion-cues.json');
  const studies = await json('design/contract/synthetic-studies.json');
  const callouts = await json('design/contract/layout-callouts.json');
  const planned = await json('design/contract/planned-assets.json');
  const docs = new Map();

  // ---------- component-states.md ----------
  {
    const out = [
      generated(['design/contract/component-states.json']),
      '',
      '# Component and state contract',
      '',
      `Contract ${code(states.contractVersion)} · design tokens ${code(states.tokenVersion)} (proposal) · asset manifest ${code(states.assetManifestVersion)} · wire protocol ${states.protocolVersion} at base commit ${code(states.baseCommit.slice(0, 7))}.`,
      '',
      'For every state of every component: the fact it may be drawn from, how it looks, and the live English words that say it. No state is told apart by color alone: every one has words, and most have an outline of their own as well. The hooks are the classes, ids and data attributes Frontend already produces',
      `(${code(states.frontendReference.branch)} at ${code(states.frontendReference.commit.slice(0, 7))}, as read by the Designer); a hook marked PROPOSED does not exist there yet and is listed in [frontend-handoff.md](frontend-handoff.md).`,
      '',
      'Nothing here is a rule. A state that would need a fact the audience views do not carry says so and points at an open decision in [README.md](README.md#open-decisions). A state that is exported and drawn by no rule says that too.',
      '',
      '## The eight required states',
      '',
      'Where each state the brief asks for appears. Each entry is a component and one of its states below, and every entry is a state the reference stylesheet really draws.',
      '',
      table(['State', 'Drawn as', 'What is not drawn, and why'], Object.entries(states.requiredStates).map(([name, list]) => [`**${name}**`, list.map(code).join(', '), states.requiredStateNotes?.[name] ?? ''])),
      '',
      '## Surfaces',
      '',
      table(['Surface', 'What it is'], Object.entries(states.surfaces).map(([name, text]) => [SURFACE[name] ?? name, text])),
      '',
      '## Components',
      '',
    ];
    for (const component of states.components) {
      out.push(`### ${component.title}`, '');
      out.push(`${code(component.id)} · ${component.audience} · ${component.surfaces.map(name => SURFACE[name] ?? name).join('; ')}`, '');
      out.push(`Hook: ${code(component.hook)}`, '');
      if (component.assets.length > 0) out.push(`Assets: ${component.assets.map(code).join(', ')}`, '');
      out.push(table(['State', 'Drawn when', 'Told apart by', 'Words'], component.states.map(state => [
        `${code(state.state)}${state.designState ? ` (${state.designState})` : ''}${state.surfaces ? ` · ${state.surfaces.map(name => SURFACE[name]).join('; ')} only` : ''}`,
        state.when + (state.note ? ` _${state.note}_` : ''),
        state.shape,
        state.words,
      ])), '');
      if (component.cues) out.push(`Cues: ${component.cues.map(id => `[${code(id)}](motion-storyboards.md#${id})`).join(', ')}`, '');
      if (component.fallback) out.push(`Missing-asset fallback: ${component.fallback}`, '');
      if (component.note) out.push(component.note, '');
      if (component.openQuestion) out.push(`Open: ${component.openQuestion}`, '');
      if (component.mustNot) out.push('Must not:', '', ...component.mustNot.map(item => `- ${item}`), '');
    }
    docs.set('docs/design/component-states.md', `${out.join('\n').trimEnd()}\n`);
  }

  // ---------- motion-storyboards.md ----------
  {
    const out = [
      generated(['design/contract/motion-cues.json', 'design/contract/synthetic-studies.json']),
      '',
      '# Motion storyboards',
      '',
      `Design tokens ${code(cues.tokenVersion)} (proposal) · wire protocol ${cues.protocolVersion}. This page applies [motion-direction.md](motion-direction.md); it does not replace it.`,
      '',
      'A storyboard frame here is not a drawing. It is the reference stylesheet ([`design/prototypes/css/cues.css`](../../design/prototypes/css/cues.css)) started at a negative delay and paused, so each frame is exactly what a browser shows at that moment of the cue. The same stylesheet plays on the motion page (`design/prototypes/motion.html`).',
      '',
      'Durations are the existing token values. They are cosmetic targets, never deadlines, and none is measured on a device. The split into opening, accent and settle is this design\'s proposal.',
      '',
      'Every cue works without art. The layers that are pictures (the ink trail, the dust, the panel\'s halftone edge, the speed lines) exist only once the public bundle has loaded; `storyboards.html?art=none` shows each cue without them.',
      '',
      '## What a cue is',
      '',
      ...cues.rules.map(rule => `- ${rule}`),
      '',
      '## Cues',
      '',
      table(['Cue', 'Director kind', 'Audience', 'Duration', 'Opening / accent / settle'], cues.cues.map(cue => [
        `[${cue.title}](#${cue.id})`,
        cue.frontendCue ? code(cue.frontendCue) : 'none: local input',
        cue.audienceTag,
        `${cue.durationMs} ms (${code(`motionMs.${cue.durationToken}`)})`,
        `${cue.beatsMs.opening} / ${cue.beatsMs.accent} / ${cue.beatsMs.settle} ms`,
      ])),
      '',
    ];
    for (const cue of cues.cues) {
      out.push(`<a id="${cue.id}"></a>`, '', `## ${cue.title}`, '');
      out.push(`![${cue.title}: opening, accent and settled frames, then reduced motion and reduced effects](../../design/review/storyboard-${cue.id}.png)`, '');
      const [opening, accent, settled] = cue.storyboardFramesMs;
      out.push(table(['', ''], [
        ['Cue', `${code(cue.id)}${cue.frontendCue ? ` · director kind ${code(cue.frontendCue)}` : ''} · ${cue.level.replaceAll('_', ' ')}`],
        ['Authorized by', cue.authorizedBy],
        ['Audience', cue.audience],
        ['Lands on', code(cue.anchor)],
        ['Duration', `${cue.durationMs} ms: ${cue.beatsMs.opening} opening, ${cue.beatsMs.accent} accent, ${cue.beatsMs.settle} settle`],
        ['Easing', Object.entries(cue.easing).map(([beat, name]) => `${beat}: ${code(`motionEasing.${name}`)}`).join(' · ')],
        ['Frames shown', `opening at ${opening} ms, accent at ${accent} ms, settled at ${settled} ms`],
        ['Layers', cue.layers.join(' ')],
        ['It says', cue.says],
        ['Reduced motion', cue.reducedMotion],
        ['Reduced effects', cue.reducedEffects],
        ['Sound', cue.audio],
        ['Without the cue', cue.fallback],
      ]), '');
      if (cue.mustNot) out.push('Must not show:', '', ...cue.mustNot.map(item => `- ${item}`), '');
    }
    out.push('## Not storyboarded in this slice', '', table(['Cue', 'Why not yet'], cues.notProduced.map(item => [`${item.title} (${code(item.id)})`, item.note])), '');

    out.push('<a id="synthetic-studies"></a>', '', '## Synthetic studies: not cues', '');
    out.push('> **No approved fact exists for what follows, and none of it is connected to anything.** The contracts carry no shot, shooter, attack type, block or Protection fact for any audience (RULE-003 / D09). The two treatments below are drawn so that they can be judged on paper while that decision is open.', '');
    out.push('What keeps them apart from the cues above:', '');
    out.push(
      '- They are not in the cue list. [`design/contract/synthetic-studies.json`](../../design/contract/synthetic-studies.json) holds them; nothing that walks the cues can reach them.',
      `- They are not assets. Their drawings are in \`design/source/studies/\`, are written to \`design/studies/\` with a manifest of their own (${code(studyManifest.manifestVersion)}), and are in no bundle. The export build refuses a recipe that reads a study source.`,
      '- One review page shows them, `design/prototypes/studies.html`, with a stylesheet and a module that no other page may load. `check-assets.mjs` refuses any other file of the review kit that reaches them, and `check-shell.mjs` refuses a shell page that requests them.',
      `- Every study file carries the mark ${code(studyManifest.devOnly)}, which Frontend's production-exclusion check looks for.`,
      '- No token exists for them. The duration is `motionMs.publicImpact` from the pinned 0.2.0 tokens, written as a number in their own stylesheet.',
      '',
      'This is a fence against accident, checked by tools. It is not a technical impossibility: someone who sets out to copy a study into a shell can. The guard against that is review.',
      '',
    );
    for (const study of studies.studies) {
      const [opening, accent, settled] = study.storyboardFramesMs;
      out.push(`<a id="${study.id}"></a>`, '', `### ${study.title} — SYNTHETIC STUDY`, '');
      out.push(`![${study.title}: a synthetic study, never connected](../../design/review/${study.id}.png)`, '');
      out.push(table(['', ''], [
        ['Study', code(study.id)],
        ['Authorized by', study.authorizedBy],
        ['Blocked by', study.gate],
        ['Where it is drawn', study.placement],
        ['Duration', `${study.durationMs} ms: ${study.beatsMs.opening} opening, ${study.beatsMs.accent} accent, ${study.beatsMs.settle} settle`],
        ['Frames shown', `opening at ${opening} ms, accent at ${accent} ms, settled at ${settled} ms`],
        ['Layers', study.layers.join(' ')],
        ['It says', study.says],
        ['If it were ever approved', study.ifEverApproved],
      ]), '');
      out.push('Must not:', '', ...study.mustNot.map(item => `- ${item}`), '');
    }
    docs.set('docs/design/motion-storyboards.md', `${out.join('\n').trimEnd()}\n`);
  }

  // ---------- layouts.md ----------
  {
    const out = [
      generated(['design/contract/layout-callouts.json']),
      '',
      '# Annotated layouts',
      '',
      'Each board is a shell at its own viewport size, drawn with the reference stylesheet. The markup follows what Frontend produces, rebuilt by hand in the Designer\'s review kit (`design/prototypes/js/kit.js`); it is not Frontend\'s code running, and it can drift from it. The numbers are placed from the elements themselves. Every state shown is synthetic: authored for looking at layout, the outcome of nothing.',
      '',
      'The images are desktop Chrome renders on one machine. They are not device measurements. `component` is the id used in [component-states.md](component-states.md).',
      '',
    ];
    for (const [name, board] of Object.entries(callouts.boards)) {
      out.push(`## ${board.title}`, '', board.note, '', `![${board.title}](../../design/review/layout-${name}.png)`, '');
      out.push(`Frames: ${board.frames.map(frame => `${frame.caption}, ${frame.width} CSS px wide`).join('; ')}${board.defaultFontPx ? `. Browser default text size ${board.defaultFontPx} px.` : '.'}`, '');
      if (board.callouts.length > 0) {
        out.push(table(['#', 'Part', 'Component', 'Drawn from'], board.callouts.map(item => [item.n, item.label, code(item.component), item.source])), '');
      }
    }
    docs.set('docs/design/layouts.md', `${out.join('\n').trimEnd()}\n`);
  }

  // ---------- asset-inventory.md ----------
  {
    const kb = bytes => (bytes < 1024 ? `${bytes} B` : `${(bytes / 1024).toFixed(1)} KB`);
    const out = [
      generated(['design/exports/asset-manifest.json', 'design/contract/planned-assets.json']),
      '',
      '# Asset inventory',
      '',
      `Asset manifest ${code(manifest.manifestVersion)} · design tokens ${code(manifest.tokenVersion)} (proposal) · base commit ${code(manifest.baseCommit.slice(0, 7))} · rule-source manifest ${code(manifest.ruleSourceManifestSha256.slice(0, 12))}…`,
      '',
      'Two kinds of thing are listed here and they are kept apart:',
      '',
      '- **Finished**: an exported file exists, is listed in the manifest with its size, anchors and hash, and is drawn on the contact sheet below.',
      '- **Not produced**: nothing exists. The entry says what it would be drawn from and what stands in for it today.',
      '',
      'Finished means the artwork is complete for this slice. It does not mean approved: human art review is pending, and nothing here has been seen on a phone or a shared display.',
      '',
      'The two synthetic disclosure studies are neither. They are not assets, are in no bundle and are not in this manifest: see [the end of this page](#synthetic-studies-not-assets).',
      '',
      '![Every export, drawn once from the file itself, and every sprite symbol](../../design/review/asset-all.png)',
      '',
      '## Rights and provenance',
      '',
      table(['', ''], Object.entries(manifest.rights).map(([key, value]) => [key, value])),
      '',
      'The editable source of every export is the layered SVG named in its row. Exports are lifted out of the sources by `design/tools/build-exports.mjs`; no export is edited by hand.',
      '',
      '## Bundles',
      '',
      'A bundle is loaded as **one stylesheet**. Every picture in it is a custom property holding the picture itself, so nothing is fetched later and what a device draws can never show in what it asks for. The separate files are the same pictures for a renderer that wants textures; it takes all of a bundle or none.',
      '',
      table(['Bundle', 'Audience', 'Its stylesheet', 'Files', 'Load policy'], Object.entries(manifest.bundles).map(([name, bundle]) => [
        code(name), bundle.audience,
        `${code(bundle.stylesheet.path.split('/').at(-1))}<br>${kb(bundle.stylesheet.bytes)}, ${bundle.stylesheet.properties} pictures`,
        `${bundle.files.length}, ${kb(bundle.bytes)}`, bundle.loadPolicy,
      ])),
      '',
      `The role bundle is expected to hold ${manifest.bundles.roles.expectedRoles.length} roles and holds ${manifest.bundles.roles.producedRoles.length}: ${manifest.bundles.roles.producedRoles.join(', ')}.`,
      '',
      '## Produced',
      '',
      table(['Asset', 'Status', 'Bundle', 'Variants', 'Size', 'Drawn from', 'Editable source'], manifest.assets.map(asset => [
        `${code(asset.id)} ${asset.version}<br>${asset.title}`,
        'Finished',
        code(asset.bundle),
        asset.variants.length,
        kb(asset.variants.reduce((total, variant) => total + variant.bytes, 0)),
        asset.dataSource,
        asset.sources.map(source => code(source.path)).join('<br>'),
      ])),
      '',
      '### Sprites',
      '',
      table(['Sprite', 'Bundle', 'Symbols', 'Size'], manifest.sprites.map(sprite => [`${code(sprite.id)} ${sprite.version}`, code(sprite.bundle), sprite.symbols.map(symbol => symbol.symbol + (symbol.tintable ? ' (tintable)' : '')).join(', '), kb(sprite.bytes)])),
      '',
      '### Variants, sizes and anchors',
      '',
      'Sizes are in the export\'s own units; every export is vector and scales freely. Anchors are in the same units, from the top left. The full list, with hashes and the surfaces each variant may be drawn on, is [`design/exports/asset-manifest.json`](../../design/exports/asset-manifest.json).',
      '',
    ];
    for (const asset of manifest.assets) {
      out.push(`**${code(asset.id)}**`, '');
      out.push(table(['Variant', 'Size', 'Bytes', 'May be drawn on', 'Anchors'], asset.variants.map(variant => [
        code(variant.variant),
        `${variant.width} × ${variant.height}`,
        variant.bytes,
        variant.surfaces.map(name => SURFACE[name]).join('; '),
        variant.anchors ? Object.entries(variant.anchors).filter(([, value]) => typeof value !== 'object' || Array.isArray(value)).map(([key, value]) => `${key} ${Array.isArray(value) ? `[${value.join(', ')}]` : value}`).join(' · ') : '',
      ])), '');
    }
    out.push('## Not produced', '', 'What a complete in-person V1 still needs from Designer. None of it exists as an asset.', '');
    for (const group of planned.groups) {
      out.push(`### ${group.group}`, '', table(['Planned id', 'What', 'Needs', 'Until then'], group.items.map(item => [code(item.id), item.title, item.needs, item.until])), '');
    }
    out.push('<a id="synthetic-studies-not-assets"></a>', '', '## Synthetic studies: not assets', '');
    out.push(`> ${studyManifest.status}`, '');
    out.push(`Study manifest ${code(studyManifest.manifestVersion)}, in [\`design/studies/\`](../../design/studies/study-manifest.json). Gate: ${studyManifest.gate}. What fences them is described in [motion-storyboards.md](motion-storyboards.md#synthetic-studies).`, '');
    out.push(table(['Study', 'Size', 'Drawn from', 'Editable source'], studyManifest.studies.map(study => [
      `${code(study.id)} ${study.version}<br>${study.title}`,
      study.variants.map(variant => `${variant.width} × ${variant.height}, ${variant.bytes} B`).join('<br>'),
      `${study.dataSource} Gate: ${study.gate}.`,
      study.sources.map(source => code(source.path)).join('<br>'),
    ])), '');
    docs.set('docs/design/asset-inventory.md', `${out.join('\n').trimEnd()}\n`);
  }

  return docs;
}
